[pytest]
norecursedirs = 
    env
    venv
    .git
    __pycache__
    .pytest_cache
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
addopts = 
    --tb=short
    -vv
    -p no:cacheprovider
    --assert=plain
    --show-capture=no
testpaths = tests/
python_files = test_*.py
python_classes = Test*
python_functions = test_*